version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: todo_service_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://todo_service_postgres_db:5432/${POSTGRES_DBNAME_KEYCLOAK}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command: start-dev
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - todo-service-network

networks:
  todo-service-network:
    name: todo-service-network
    external: true