version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todo_service_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      KEYCLOAK_DB: ${POSTGRES_DBNAME_KEYCLOAK}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo-service-network

volumes:
  postgres_data:

    

networks:
  todo-service-network:
    name: todo-service-network
    driver: bridge
  